---
collections:
# With just the collection name
- name: community.general
  type: galaxy
- name: prometheus.prometheus
  type: galaxy
- name: devsec.hardening
  type: galaxy
- name: maxhoesel.caddy

roles:
- name: cloudalchemy.grafana

# EXTRAS
- name: jnv.unattended-upgrades
  version: v1.7.1
